[build]
  publish = "."
  command = "pip install -r requirements.txt && streamlit run app.py --server.port $PORT --server.headless true"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
