# secrets.toml template
# Replace YOUR_GOOGLE_API_KEY with your actual Google Generative AI API key
GEMINI_API_KEY = "AIzaSyDoNRjwGMrAZkQax8lrz4wYi8AYW0wFrY8"

# Instructions:
# 1. Copy this content to .streamlit/secrets.toml
# 2. Replace YOUR_GOOGLE_API_KEY with your actual API key
# 3. When deploying to Streamlit Community Cloud, upload this file through their secrets interface
